apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: Z2hwX1hWTkpjTGc0Y3c3NVU4Z1ZhU2dZbGluTFB0MDB0ejJoN3BETg==
# TODO This token is coded in base64 and will be outdate in 60 days from Nov 18 2022